<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62788" started-at="2019-11-17T17:05:04 IST" finished-at="2019-11-17T17:06:07 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62788" started-at="2019-11-17T17:05:04 IST" finished-at="2019-11-17T17:06:07 IST">
      <class name="TestScripts.SortTableTest">
        <test-method status="PASS" signature="openAppication()[pri:0, instance:TestScripts.SortTableTest@69a10787]" name="openAppication" is-config="true" duration-ms="15151" started-at="2019-11-17T17:05:05 IST" finished-at="2019-11-17T17:05:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppication -->
        <test-method status="FAIL" signature="sortTable()[pri:0, instance:TestScripts.SortTableTest@69a10787]" name="sortTable" duration-ms="44259" started-at="2019-11-17T17:05:20 IST" finished-at="2019-11-17T17:06:04 IST">
          <exception class="com.applitools.eyes.exceptions.DiffsFoundException">
            <message>
              <![CDATA[Test 'sortTable' of 'Hacka V1 application' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251828310263951/00000251828310263693?accountId=p8Z0pjqbDke54B7_7ErUOw~~]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'sortTable' of 'Hacka V1 application' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251828310263951/00000251828310263693?accountId=p8Z0pjqbDke54B7_7ErUOw~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at Generic.BaseTest.validateWindow(BaseTest.java:63)
at TestScripts.SortTableTest.sortTable(SortTableTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.exceptions.DiffsFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sortTable -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:TestScripts.SortTableTest@69a10787]" name="closeApplication" is-config="true" duration-ms="3020" started-at="2019-11-17T17:06:04 IST" finished-at="2019-11-17T17:06:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sortTable status=FAILURE method=SortTableTest.sortTable()[pri:0, instance:TestScripts.SortTableTest@69a10787] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- TestScripts.SortTableTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
